---
# tasks file for ntp_client

- name: ENSURE PACKAGES ARE INSTALLED
  package:
    name: "{{ ntp_client['packages'] }}"
  tags:
    - ntp
    - chrony

- name: ENSURE CONFIGURATION IS UP TO DATE
  template:
    src: "{{ ntp_client['config']['template']['src'] }}"
    dest: "{{ ntp_client['config']['template']['dest'] }}"
    owner: "{{ ntp_client['config']['template']['owner'] }}"
    group: "{{ ntp_client['config']['template']['group'] }}"
    mode: "{{ ntp_client['config']['template']['mode'] }}"
    backup: "{{ ntp_client['config']['template']['backup'] }}"
  notify: restart ntp client
  tags:
    - ntp
    - chrony

- name: "ENSURE NTP DAEMON BOOT STATE IS CONFIGURED ({{ ntp_client['service']['enabled'] }})"
  service:
    name: "{{ ntp_client['service']['name'] }}"
    enabled: "{{ ntp_client['service']['enabled'] }}"
  tags:
    - ntp
    - chrony

- name: "ENSURE NTP DAEMON IS IN DESIRED STATE ({{ ntp_client['service']['state'] }})"
  service:
    name: "{{ ntp_client['service']['name'] }}"
    state: "{{ ntp_client['service']['state'] }}"
  tags:
    - ntp
    - chrony
