---
# tasks file for ntp_client

- name: ENSURE PACKAGES ARE INSTALLED
  package:
    name: "{{ ntp_client_packages }}"
  tags:
    - ntp
    - chrony

- name: ENSURE CONFIGURATION IS UP TO DATE
  template:
    src: "{{ ntp_client_template_src }}"
    dest: "{{ ntp_client_template_dest }}"
    owner: "{{ ntp_client_template_owner }}"
    group: "{{ ntp_client_template_group }}"
    mode: "{{ ntp_client_template_mode }}"
    backup: "{{ ntp_client_template_backup }}"
  notify: restart ntp client
  tags:
    - ntp
    - chrony

- name: "ENSURE NTP DAEMON BOOT STATE IS CONFIGURED ({{ ntp_client_service_enabled }})"
  service:
    name: "{{ ntp_client_service_name }}"
    enabled: "{{ ntp_client_service_enabled }}"
  tags:
    - ntp
    - chrony

- name: "ENSURE NTP DAEMON IS IN DESIRED STATE ({{ ntp_client_service_state }})"
  service:
    name: "{{ ntp_client_service_name }}"
    state: "{{ ntp_client_service_state }}"
  tags:
    - ntp
    - chrony
